package config

const REQ = "REQ"

const ACK = "ACK"

const REL = "REL"

const DEMANDE = "DEMANDE"
const ATTENTE = "ATTENTE"

const VALUE = "VALUE"

const USERS = "USERS"

const ADD_USER = "ADD_USER"

const ADD_AUCTION = "ADD_AUCTION"

const REMOVE_AUCTION = "REMOVE_AUCTION"

const INCREMENT_AUCTION_IDS = "INCREMENT_AUCTION_IDS"

const NOTIFY_NEWAUCTION = "NOTIFY_NEWAUCTION"

const NOTIFY_SUBSCRIBED = "NOTIFY_SUBSCRIBED"

const NOTIFY_END = "NOTIFY_END"

const CHANGE_WINNER = "CHANGE_WINNER"

const CHANGE_PRICE = "CHANGE_PRICE"

const FIN  = "FIN"

const AUTORISATION = "OK"

const UPDATE = "UPDATE"
