package config

const REQ = "REQ"

const ACK = "ACK"

const REL = "REL"

const DEMANDE = "DEMANDE"
const ATTENTE = "ATTENTE"

const VALUE = "VALUE"

const USERS = "USERS"

const ADD_USER = "ADD_USER"

const ADD_AUCTION = "ADD_AUCTION"

const REMOVE_AUCTION = "REMOVE_AUCTION"

const ADD_SUBSCRIPTION = "ADD_SUBSCRIPTION"

const REMOVE_SUBSCRIPTION = "REMOVE_SUBSCRIPTION"

const ADD_NEWAUCTION = "ADD_NEWAUCTION"

const REMOVE_NEWAUCTION = "REMOVE_NEWAUCTION"

const FIN  = "FIN"

const AUTORISATION = "OK"

const UPDATE = "UPDATE"
